apiVersion: v1 
kind: ReplicationController 
metadata: 
  name: nginx-rc
  namespace: kube-system
spec: 
  replicas: 1
  selector: 
    name: nginx
  template: 
    metadata: 
      labels: 
        name: nginx
    spec: 
      containers: 
        - name: nginx
          image: docker.io/nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
